### ISSUE TITLE
Cannot save (update) existing record

### ISSUE THREAD

**Issue by ehannes** [my-codeworks/fortnox-api#37]
```
  2) Fortnox::API::Repository::Customer#save old (update existing) include updated "Name"
     Failure/Error: message += "\n\n#{response.request.inspect}" if Fortnox::API.debugging
     
     NoMethodError:
       undefined method `debugging' for Fortnox::API:Module
     Shared Example Group: "save" called from ./spec/fortnox/api/repositories/customer_spec.rb:72
     # ./lib/fortnox/api/request_handling.rb:10:in `raise_api_error'
     # ./lib/fortnox/api/request_handling.rb:19:in `validate_response'
     # ./lib/fortnox/api/request_handling.rb:23:in `validate_and_parse'
     # ./lib/fortnox/api/request_handling.rb:30:in `execute'
     # ./lib/fortnox/api/base.rb:37:in `block (2 levels) in <class:Base>'
     # ./lib/fortnox/api/repositories/base/savers.rb:18:in `save_new'
     # ./lib/fortnox/api/repositories/base/savers.rb:12:in `save'
     # ./spec/fortnox/api/repositories/customer_spec.rb:77:in `block (6 levels) in <top (required)>'
     # ./spec/fortnox/api/repositories/customer_spec.rb:77:in `block (5 levels) in <top (required)>'
     # ./spec/fortnox/api/repositories/customer_spec.rb:51:in `block (4 levels) in <top (required)>'
```
